nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: 585df285-d233-3d07-9f5e-18de619845eb

npmRegistryServer: "https://nexus.cfdp.fr/repository/npm-all/"

yarnPath: .yarn/releases/yarn-berry.cjs
